name: Deploy to GitHub Pages

on:
  workflow_run:
    workflows: [".NET"]
    branches:
      - main
    types:
      - completed
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps: 
      - uses: actions/checkout@v4
      
      - name: Use Node.js version 20
        uses: actions/setup-node@v4
        with: 
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build -- --base-href=/realworld-state

      - name: Deploy GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: ./dist/realworld-state-test/browser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
      
      
