name: Deploy to GitHub Pages

on:
  workflow_run:
    workflows: [".NET"]
    branches:
      - main
    types:
      - completed
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: Use Node.js version 20
        uses: actions/setup-node@v4
        with: 
          node-version: '20'
      - name: Build and Deploy GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v2
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BASE_BRANCH: main
          BRANCH: gh-pages
          FOLDER: dist/realworld-state-test/browser
          BUILD_SCRIPT: npm install && npm run build -- --base-href=/realworld-state
      
      
      
